version: '3.7'

services:
  agriscrapper:
    container_name: agriscrapper
    build: ./agriscrapper/.
    volumes:
      - ./agriscrapper:/app
    networks:
      - agriscrapper_network
    
  dashboard:
    container_name: dashboard
    build: ./dashboard/.
    volumes:
      - ./dashboard:/app
    networks:
      - agriscrapper_network

  data_lake_db:
    container_name: data_lake_db
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: data_lake
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456#data_lake_db_password
    volumes:
      - ./data_lake_db_data:/var/lib/postgresql/data
    networks:
      - agriscrapper_network

  analytics_db:
    container_name: analytics_db
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456#analytics_db_password
    volumes:
      - ./analytics_db_data:/var/lib/postgresql/data
    networks:
      - agriscrapper_network

networks:
  agriscrapper_network:
    name: agriscrapper_network
    driver: bridge
